#!/bin/sh
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
#获取上层目录
cur_dir=$(dirname $(pwd))
#cur_dir=$(dirname $cur_dir)

#脚本目录
flutter_module_path=$(pwd)
target_web_package=$flutter_module_path/package
build_dir=$flutter_module_path/build/web

echo "flutter项目地址:$flutter_module_path"
echo "build_dir:$target_flutter_repo_path"

echo "切换到$flutter_module_path,开始打包"
#脚本所在目录
cd $flutter_module_path

#先清理
echo "清理缓存文件:$build_dir"
rm -rf $build_dir

echo "开始打包..."
#flutter build aar --no-profile --no-pub --build-number 1.0.2 --output-dir=$build_dir
flutter build web --web-renderer=canvaskit --dart-define=FLUTTER_WEB_CANVASKIT_URL=http://dev.cnsuning.com:8000/package/bin/
#flutter build web --web-renderer=html --release
if [ $? -ne 0 ]; then
    echo "打包失败"
    exit 0
fi

#flutter build aar --no-debug --no-profile --no-pub --target-platform android-arm,android-arm64 --build-number 1.0.1
echo "打包完成"

echo "copy ${target_web_package} to $build_dir"
cp -r $target_web_package $build_dir
if [ $? -ne 0 ]; then
    echo "拷贝失败"
    exit 0
fi
