name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          
      - name: Enable web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build and test
        run: flutter build web --release
    
      - name: Copy to docs/web
        run: |
          mkdir -p docs/web
          cp -R build/web/* docs/web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/web/

    
